# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nnDowYieMJD8wzT5Zg3rRaw3MEhJ4dTs
"""

import json #Imports the json module for JSON parsing.
from functools import reduce #For merging DataFrames iteratively in the main function
from typing import Dict, List, Optional  #type hints for better code readability

import pandas as pd #for DataFrame creation and data manipulation.
import requests #This library for making HTTP requests to the World Bank API.
from requests.exceptions import HTTPError, RequestException #Imports specific exception classes for handling HTTP and request errors.
import time #Imports the time module for adding delays during retry attempts for rate limiting.

INDICATORS = { #Defines a dictionary mapping human-readable indicator names to World Bank API codes.
    "population": "SP.POP.TOTL",#Maps "population" to the API code for total population.
    "growth_rate": "SP.POP.GROW",#Maps "growth_rate" to the API code for population growth rate
    "area": "AG.LND.TOTL.K2",#Maps "area" to the API code for total land area in square kilometers.
    "density": "EN.POP.DNST", #Maps "density" to the API code for population density.
} #Closes the INDICATORS dictionary definition.

API_TEMPLATE = (#Begins a string template for the World Bank API endpoint URL.
    "https://api.worldbank.org/v2/country/all/indicator/{indicator}" #Specifies the base URL for fetching indicator data for all countries.
   "?format=json&MRV=1&per_page=20000" #Adds query parameters for JSON format, most recent value, and 20,000 results per page.
) #Closes the API_TEMPLATE string definition.

def fetch_indicator(indicator_code: str, session: Optional[requests.Session] = None) -> pd.DataFrame:#Defines a function to fetch an indicator’s data, with type hints for input and output.Documents the function’s purpose: fetching the most recent data as a DataFrame.

    url = API_TEMPLATE.format(indicator=indicator_code)#Formats the API URL by inserting the indicator code into the template.
    sess = session or requests.Session()#Uses the provided session or creates a new one for HTTP requests.
    max_retries = 3 #Sets the maximum number of retry attempts for handling rate limit errors.
    retry_delay = 5  # Defines a 5-second delay between retry attempts.

    for attempt in range(max_retries):#Starts a loop to attempt the API request up to max_retries times.
        try:#Begins a try block to handle potential HTTP or request errors
            r = sess.get(url, timeout=30)#Sends a GET request to the API with a 30-second timeout.
            r.raise_for_status()#Raises an HTTPError if the response status code indicates an error
            payload = r.json()#Parses the JSON response into a Python dictionary.
            if not isinstance(payload, list) or len(payload) < 2 or payload[1] is None:#Checks if the response is invalid (not a list, too short, or contains no data).
                return pd.DataFrame(columns=["country", "value"])#Returns an empty DataFrame if the response is invalid.
            rows = []#Initializes an empty list to store parsed data rows.
            for rec in payload[1]:#Loops through the data entries in the second element of the JSON payload.
                rows.append(#Begins appending a dictionary to the rows list for each data entry.
                    {#Opens a dictionary for a single row of country data.
                        "country": rec.get("country", {}).get("value"),#Extracts the country code from the nested country dictionary, safely handling missing keys.
                        "iso3": rec.get("countryiso3code"),#Extracts the ISO3 country code, allowing for None if missing.
                        "value": rec.get("value"),#Extracts the indicator value, allowing for None if missing.
                    }#Closes the dictionary for the row.
                )#Closes the append call for the row.
            df = pd.DataFrame(rows)#Creates a pandas DataFrame from the list of rows.
            df = df.drop_duplicates(subset=["iso3"]).reset_index(drop=True)#Removes duplicate rows based on ISO3 code and resets the index.
            return df#Returns the processed DataFrame with the indicator data.
        except HTTPError as e:#Catches HTTP errors raised by raise_for_status().
            if r.status_code == 429:#Checks if the error is a 429 (Too Many Requests) status code for rate limiting.
                if attempt < max_retries - 1:#Ensures there are retries left before proceeding.
                    print(f"Rate limit exceeded for {indicator_code}. Retrying in {retry_delay} seconds...")#Prints a message indicating a retry attempt for rate limiting.
                    time.sleep(retry_delay)#Pauses execution for the specified delay to respect rate limits.
                    continue#Continues to the next loop iteration to retry the request.
                else:#Handles the case where maximum retries are exhausted.
                    print(f"Max retries reached for {indicator_code} (status 429). Returning empty DataFrame.")#Notifies that retries failed and an empty DataFrame will be returned.
                    return pd.DataFrame(columns=["country", "value"])#Returns an empty DataFrame for failed 429 errors.
            else:#Handles other HTTP errors (e.g., 404 for invalid endpoint).
                print(f"HTTP error for {indicator_code}: {r.status_code}. Returning empty DataFrame.")#Notifies of the specific HTTP error and status code.
                return pd.DataFrame(columns=["country", "value"])#Returns an empty DataFrame for other HTTP errors.
        except RequestException as e:#Catches general request exceptions (e.g., network issues, timeouts).
            print(f"Request failed for {indicator_code}: {e}. Returning empty DataFrame.")#Notifies of the request failure with the error message.
            return pd.DataFrame(columns=["country", "value"])#Returns an empty DataFrame for request failures.

def main(out_path: str, limit: Optional[int] = None):#Defines the main function to orchestrate data fetching and saving, with optional row limit.
    session = requests.Session()#Creates a session for reusing HTTP connections across requests.

    dfs: List[pd.DataFrame] = []#Initializes an empty list to store DataFrames for each indicator.
    for field, code in INDICATORS.items():#Iterates over the INDICATORS dictionary to fetch each indicator.
        print(f"Fetching {field} ({code}) ...")#Prints a progress message for the current indicator being fetched.
        df = fetch_indicator(code, session=session)#Calls fetch_indicator to retrieve data for the current indicator.
        df = df.rename(columns={"value": field})#Renames the "value" column to the indicator’s human-readable name.
        dfs.append(df)#Appends the DataFrame to the list of DataFrames.

    # Merge on iso3 + country
    combined = reduce(#Begins merging all DataFrames using reduce.
        lambda left, right: pd.merge(left, right, on=["iso3", "country"], how="outer"),#Defines a merge function to combine DataFrames on ISO3 and country with an outer join.
        dfs,#Specifies the list of DataFrames to merge.
    )#Closes the reduce call to create a combined DataFrame.

    # Reorder and (optionally) limit rows
    cols = ["country", "population", "growth_rate", "area", "density"]#Defines the desired column order for the final output.
    combined = combined[["country", "iso3"] + cols[1:]]  # keep iso3 temporarily
    combined = combined.sort_values("country").reset_index(drop=True)#Sorts the DataFrame by country and resets the index.

    if limit:#Checks if a row limit is specified.
        combined = combined.head(limit)#Limits the DataFrame to the specified number of rows.

    combined = combined[cols]#Drops the ISO3 column and keeps only the final columns.

    # Drop rows with any missing values
    combined = combined.dropna()


    combined.to_csv(out_path, index=False, encoding="utf-8")#Saves the DataFrame to a CSV file without the index, using UTF-8 encoding.
    print(f"Saved {len(combined)} rows to {out_path}")#Prints a confirmation message with the number of rows saved.

main(out_path="worldbank_country_stats.csv", limit=None)#Calls the main function to run the script, saving output to worldbank_country_stats.csv with no row limit.